export type JobSource = 'LinkedIn' | 'Indeed' | 'Company site'
export type WorkStyle = 'Remote' | 'Hybrid' | 'On-site'
export type Seniority = 'junior' | 'mid' | 'senior' | 'lead'

export type Job = {
  id: string
  title: string
  company: string
  city: string
  province: string
  workStyle: WorkStyle
  source: JobSource
  applyUrl?: string
  scoreHint?: number
  skills: string[]
  seniority: Seniority
  salary: string
  postedDaysAgo: number
  closesInDays: number
  applicants: number
  summary: string
  whyFits?: string
  watchFor?: string
  briefed?: boolean
  deeper?: boolean
}

export const JOBS: Job[] = [
  {
    id: 'shopify-frontend',
    title: 'Frontend Engineer',
    company: 'Shopify',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['react', 'typescript', 'javascript', 'css', 'next.js', 'graphql', 'accessibility'],
    seniority: 'mid',
    salary: '$115k–$150k CAD',
    postedDaysAgo: 1,
    closesInDays: 12,
    applicants: 48,
    summary: 'Build merchant-facing UI used by millions. Strong React and product sense required.',
  },
  {
    id: 'wealthsimple-product-eng',
    title: 'Product Engineer',
    company: 'Wealthsimple',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Remote',
    source: 'Indeed',
    skills: ['typescript', 'react', 'node', 'product', 'fintech', 'sql', 'experimentation'],
    seniority: 'mid',
    salary: '$120k–$155k CAD',
    postedDaysAgo: 2,
    closesInDays: 9,
    applicants: 36,
    summary: 'Own features end to end for a consumer finance product used across Canada.',
  },
  {
    id: 'ada-senior-ui',
    title: 'Senior UI Engineer',
    company: 'Ada',
    city: 'Ottawa',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'Company site',
    skills: ['react', 'typescript', 'design systems', 'css', 'storybook', 'accessibility', 'figma'],
    seniority: 'senior',
    salary: '$130k–$165k CAD',
    postedDaysAgo: 3,
    closesInDays: 6,
    applicants: 22,
    summary: 'Lead UI quality for an AI customer-service platform. Design-system fluency is a plus.',
  },
  {
    id: 'ssense-fullstack',
    title: 'Full Stack Engineer',
    company: 'SSENSE',
    city: 'Montreal',
    province: 'QC',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['javascript', 'typescript', 'node', 'react', 'aws', 'sql', 'e-commerce'],
    seniority: 'mid',
    salary: '$105k–$140k CAD',
    postedDaysAgo: 1,
    closesInDays: 14,
    applicants: 61,
    summary: 'Ship storefront and ops tools for a global fashion retailer.',
  },
  {
    id: 'hootsuite-frontend',
    title: 'Senior Frontend Engineer',
    company: 'Hootsuite',
    city: 'Vancouver',
    province: 'BC',
    workStyle: 'Remote',
    source: 'Indeed',
    skills: ['react', 'typescript', 'redux', 'testing', 'css', 'webpack', 'product'],
    seniority: 'senior',
    salary: '$125k–$160k CAD',
    postedDaysAgo: 4,
    closesInDays: 8,
    applicants: 41,
    summary: 'Modernize a high-traffic social suite used by marketing teams worldwide.',
  },
  {
    id: 'rbc-software',
    title: 'Software Developer',
    company: 'RBC',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['java', 'spring', 'sql', 'api', 'cloud', 'testing', 'agile'],
    seniority: 'mid',
    salary: '$95k–$125k CAD',
    postedDaysAgo: 2,
    closesInDays: 18,
    applicants: 112,
    summary: 'Build internal platforms that move money safely for millions of Canadians.',
  },
  {
    id: 'nubank-backend',
    title: 'Backend Engineer',
    company: 'Nubank',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Remote',
    source: 'Company site',
    skills: ['java', 'kotlin', 'microservices', 'sql', 'aws', 'distributed systems', 'api'],
    seniority: 'senior',
    salary: '$140k–$180k CAD',
    postedDaysAgo: 0,
    closesInDays: 5,
    applicants: 19,
    summary: 'Scale core banking services. Distributed systems experience is the bar.',
    deeper: true,
  },
  {
    id: 'open-text-pm',
    title: 'Product Manager',
    company: 'OpenText',
    city: 'Waterloo',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'Indeed',
    skills: ['product', 'roadmaps', 'saas', 'analytics', 'stakeholder', 'agile', 'research'],
    seniority: 'mid',
    salary: '$110k–$145k CAD',
    postedDaysAgo: 5,
    closesInDays: 11,
    applicants: 54,
    summary: 'Own a slice of enterprise content software used by global IT teams.',
  },
  {
    id: 'figma-canada-design',
    title: 'Product Designer',
    company: 'Figma',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Remote',
    source: 'LinkedIn',
    skills: ['figma', 'product design', 'prototyping', 'research', 'design systems', 'ui', 'ux'],
    seniority: 'mid',
    salary: '$120k–$155k CAD',
    postedDaysAgo: 1,
    closesInDays: 10,
    applicants: 73,
    summary: 'Design collaboration tools for teams that already live in Figma.',
  },
  {
    id: 'shopify-data',
    title: 'Data Analyst',
    company: 'Shopify',
    city: 'Ottawa',
    province: 'ON',
    workStyle: 'Remote',
    source: 'Company site',
    skills: ['sql', 'python', 'tableau', 'excel', 'analytics', 'statistics', 'dashboards'],
    seniority: 'mid',
    salary: '$90k–$120k CAD',
    postedDaysAgo: 3,
    closesInDays: 7,
    applicants: 88,
    summary: 'Turn merchant data into decisions for product and go-to-market teams.',
  },
  {
    id: 'lululemon-marketing',
    title: 'Digital Marketing Manager',
    company: 'lululemon',
    city: 'Vancouver',
    province: 'BC',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['marketing', 'seo', 'paid social', 'analytics', 'content', 'brand', 'campaigns'],
    seniority: 'mid',
    salary: '$95k–$125k CAD',
    postedDaysAgo: 2,
    closesInDays: 13,
    applicants: 67,
    summary: 'Plan and measure campaigns that drive traffic without buying vanity reach.',
  },
  {
    id: 'td-cyber',
    title: 'Cybersecurity Analyst',
    company: 'TD',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'Indeed',
    skills: ['security', 'siem', 'python', 'network', 'incident response', 'risk', 'cloud'],
    seniority: 'mid',
    salary: '$100k–$130k CAD',
    postedDaysAgo: 4,
    closesInDays: 16,
    applicants: 45,
    summary: 'Detect and respond to threats across a large Canadian bank environment.',
  },
  {
    id: 'dialogue-fullstack',
    title: 'Full Stack Developer',
    company: 'Telus Health',
    city: 'Montreal',
    province: 'QC',
    workStyle: 'Remote',
    source: 'Company site',
    skills: ['react', 'node', 'typescript', 'healthcare', 'api', 'sql', 'aws'],
    seniority: 'mid',
    salary: '$100k–$135k CAD',
    postedDaysAgo: 0,
    closesInDays: 4,
    applicants: 17,
    summary: 'Ship virtual-care features that clinicians and patients use the same day.',
    deeper: true,
  },
  {
    id: 'cibc-ba',
    title: 'Business Analyst',
    company: 'CIBC',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['business analysis', 'sql', 'requirements', 'stakeholder', 'agile', 'excel', 'process'],
    seniority: 'mid',
    salary: '$85k–$110k CAD',
    postedDaysAgo: 6,
    closesInDays: 20,
    applicants: 96,
    summary: 'Translate business needs into clear tickets for digital banking squads.',
  },
  {
    id: 'wealthsimple-ops',
    title: 'Operations Specialist',
    company: 'Wealthsimple',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'Indeed',
    skills: ['operations', 'excel', 'customer', 'process', 'compliance', 'fintech', 'communication'],
    seniority: 'junior',
    salary: '$65k–$85k CAD',
    postedDaysAgo: 2,
    closesInDays: 15,
    applicants: 140,
    summary: 'Keep client operations accurate as the product grows.',
  },
  {
    id: 'google-canada-swe',
    title: 'Software Engineer',
    company: 'Google',
    city: 'Waterloo',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['python', 'c++', 'algorithms', 'distributed systems', 'testing', 'linux', 'java'],
    seniority: 'mid',
    salary: '$145k–$190k CAD',
    postedDaysAgo: 3,
    closesInDays: 21,
    applicants: 210,
    summary: 'Work on infrastructure used far beyond Canada. Interview bar is high and honest.',
  },
  {
    id: 'amazon-pm',
    title: 'Technical Program Manager',
    company: 'Amazon',
    city: 'Vancouver',
    province: 'BC',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['program management', 'technical', 'stakeholder', 'roadmaps', 'aws', 'communication', 'agile'],
    seniority: 'senior',
    salary: '$135k–$175k CAD',
    postedDaysAgo: 5,
    closesInDays: 12,
    applicants: 58,
    summary: 'Coordinate multi-team launches with clear owners and dates.',
  },
  {
    id: 'thinkific-growth',
    title: 'Growth Marketer',
    company: 'Thinkific',
    city: 'Vancouver',
    province: 'BC',
    workStyle: 'Remote',
    source: 'Company site',
    skills: ['growth', 'seo', 'analytics', 'experimentation', 'content', 'saas', 'paid acquisition'],
    seniority: 'mid',
    salary: '$90k–$120k CAD',
    postedDaysAgo: 1,
    closesInDays: 8,
    applicants: 33,
    summary: 'Find channels that convert course creators without buying expensive vanity traffic.',
    deeper: true,
  },
  {
    id: 'clio-eng',
    title: 'Software Engineer',
    company: 'Clio',
    city: 'Vancouver',
    province: 'BC',
    workStyle: 'Remote',
    source: 'Indeed',
    skills: ['ruby', 'rails', 'javascript', 'react', 'sql', 'saas', 'testing'],
    seniority: 'mid',
    salary: '$110k–$145k CAD',
    postedDaysAgo: 2,
    closesInDays: 11,
    applicants: 39,
    summary: 'Improve legal practice software used by firms across North America.',
  },
  {
    id: 'd2l-qa',
    title: 'QA Engineer',
    company: 'D2L',
    city: 'Kitchener',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['qa', 'testing', 'cypress', 'selenium', 'api', 'agile', 'javascript'],
    seniority: 'mid',
    salary: '$80k–$105k CAD',
    postedDaysAgo: 4,
    closesInDays: 14,
    applicants: 29,
    summary: 'Protect a learning platform used by schools and enterprises.',
  },
  {
    id: 'benevity-frontend',
    title: 'Frontend Developer',
    company: 'Benevity',
    city: 'Calgary',
    province: 'AB',
    workStyle: 'Remote',
    source: 'Company site',
    skills: ['react', 'javascript', 'typescript', 'css', 'accessibility', 'testing', 'saas'],
    seniority: 'mid',
    salary: '$95k–$125k CAD',
    postedDaysAgo: 0,
    closesInDays: 3,
    applicants: 14,
    summary: 'Build giving-platform UI. Accessibility is not optional here.',
    deeper: true,
  },
  {
    id: 'atb-data-eng',
    title: 'Data Engineer',
    company: 'ATB Financial',
    city: 'Calgary',
    province: 'AB',
    workStyle: 'Hybrid',
    source: 'Indeed',
    skills: ['python', 'sql', 'spark', 'airflow', 'aws', 'etl', 'data warehouse'],
    seniority: 'senior',
    salary: '$115k–$150k CAD',
    postedDaysAgo: 3,
    closesInDays: 9,
    applicants: 27,
    summary: 'Build reliable pipelines for a province-scale financial institution.',
  },
  {
    id: 'cgi-consultant',
    title: 'IT Consultant',
    company: 'CGI',
    city: 'Ottawa',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['consulting', 'sql', 'requirements', 'communication', 'agile', 'security', 'government'],
    seniority: 'mid',
    salary: '$85k–$115k CAD',
    postedDaysAgo: 7,
    closesInDays: 22,
    applicants: 77,
    summary: 'Deliver systems work for public-sector clients who need clarity, not slides.',
  },
  {
    id: 'lightspeed-sales',
    title: 'Account Executive',
    company: 'Lightspeed',
    city: 'Montreal',
    province: 'QC',
    workStyle: 'Hybrid',
    source: 'Indeed',
    skills: ['sales', 'saas', 'crm', 'negotiation', 'pipeline', 'communication', 'retail'],
    seniority: 'mid',
    salary: '$80k–$140k CAD OTE',
    postedDaysAgo: 2,
    closesInDays: 10,
    applicants: 51,
    summary: 'Sell commerce software to retailers who are tired of clunky POS tools.',
  },
  {
    id: 'wave-accountant',
    title: 'Staff Accountant',
    company: 'Wave',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Remote',
    source: 'Company site',
    skills: ['accounting', 'excel', 'quickbooks', 'gaap', 'reconciliation', 'finance', 'communication'],
    seniority: 'mid',
    salary: '$70k–$90k CAD',
    postedDaysAgo: 1,
    closesInDays: 12,
    applicants: 44,
    summary: 'Keep books clean for a product built for small Canadian businesses.',
    deeper: true,
  },
  {
    id: 'koho-mobile',
    title: 'Mobile Engineer',
    company: 'KOHO',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['react native', 'typescript', 'ios', 'android', 'mobile', 'fintech', 'testing'],
    seniority: 'mid',
    salary: '$110k–$145k CAD',
    postedDaysAgo: 2,
    closesInDays: 7,
    applicants: 31,
    summary: 'Ship a consumer banking app used by people who want simpler money tools.',
  },
  {
    id: 'loblaw-ux',
    title: 'UX Researcher',
    company: 'Loblaw Digital',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'Indeed',
    skills: ['research', 'ux', 'interviews', 'usability', 'analytics', 'figma', 'communication'],
    seniority: 'mid',
    salary: '$90k–$120k CAD',
    postedDaysAgo: 5,
    closesInDays: 13,
    applicants: 26,
    summary: 'Study how Canadians shop grocery and pharmacy online — then change the product.',
  },
  {
    id: 'canada-life-cs',
    title: 'Customer Success Manager',
    company: 'Canada Life',
    city: 'Winnipeg',
    province: 'MB',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['customer success', 'saas', 'communication', 'onboarding', 'retention', 'excel', 'stakeholder'],
    seniority: 'mid',
    salary: '$75k–$100k CAD',
    postedDaysAgo: 3,
    closesInDays: 17,
    applicants: 38,
    summary: 'Help group-benefits clients actually use what they bought.',
  },
  {
    id: 'suncor-analyst',
    title: 'Financial Analyst',
    company: 'Suncor',
    city: 'Calgary',
    province: 'AB',
    workStyle: 'On-site',
    source: 'Indeed',
    skills: ['finance', 'excel', 'modeling', 'forecasting', 'sap', 'variance', 'communication'],
    seniority: 'mid',
    salary: '$85k–$110k CAD',
    postedDaysAgo: 6,
    closesInDays: 19,
    applicants: 42,
    summary: 'Own forecasts and variance stories for an energy operator.',
  },
  {
    id: 'shopify-support',
    title: 'Merchant Support Specialist',
    company: 'Shopify',
    city: 'Ottawa',
    province: 'ON',
    workStyle: 'Remote',
    source: 'LinkedIn',
    skills: ['support', 'communication', 'e-commerce', 'troubleshooting', 'writing', 'crm', 'empathy'],
    seniority: 'junior',
    salary: '$55k–$72k CAD',
    postedDaysAgo: 1,
    closesInDays: 9,
    applicants: 190,
    summary: 'Help merchants get unstuck. Clear writing matters more than jargon.',
  },
  {
    id: 'notion-canada-eng',
    title: 'Full Stack Engineer',
    company: 'Notion',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Remote',
    source: 'Company site',
    skills: ['typescript', 'react', 'node', 'postgres', 'product', 'performance', 'design'],
    seniority: 'senior',
    salary: '$150k–$195k CAD',
    postedDaysAgo: 0,
    closesInDays: 5,
    applicants: 28,
    summary: 'Work on the product millions of teams already open every morning.',
    deeper: true,
  },
  {
    id: 'rbc-ux',
    title: 'Product Designer',
    company: 'RBC',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['figma', 'ux', 'ui', 'design systems', 'research', 'accessibility', 'fintech'],
    seniority: 'mid',
    salary: '$95k–$125k CAD',
    postedDaysAgo: 4,
    closesInDays: 14,
    applicants: 55,
    summary: 'Design money experiences that have to work for every Canadian, not just power users.',
  },
  {
    id: 'hubspot-csm',
    title: 'Customer Success Manager',
    company: 'HubSpot',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Remote',
    source: 'Indeed',
    skills: ['customer success', 'saas', 'crm', 'onboarding', 'communication', 'retention', 'analytics'],
    seniority: 'mid',
    salary: '$80k–$110k CAD',
    postedDaysAgo: 2,
    closesInDays: 11,
    applicants: 64,
    summary: 'Make sure Canadian mid-market teams get value in the first 90 days.',
  },
  {
    id: 'coveo-ml',
    title: 'Machine Learning Engineer',
    company: 'Coveo',
    city: 'Montreal',
    province: 'QC',
    workStyle: 'Hybrid',
    source: 'Company site',
    skills: ['python', 'machine learning', 'search', 'nlp', 'aws', 'spark', 'ranking'],
    seniority: 'senior',
    salary: '$140k–$180k CAD',
    postedDaysAgo: 3,
    closesInDays: 8,
    applicants: 21,
    summary: 'Improve ranking quality for enterprise search — relevance is the product.',
  },
  {
    id: 'fairfax-legal',
    title: 'Corporate Counsel',
    company: 'Fairfax',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['legal', 'contracts', 'corporate', 'compliance', 'negotiation', 'writing', 'finance'],
    seniority: 'senior',
    salary: '$150k–$200k CAD',
    postedDaysAgo: 8,
    closesInDays: 24,
    applicants: 18,
    summary: 'Support deal work and day-to-day commercial questions for an investment firm.',
  },
  {
    id: 'aircanada-ops',
    title: 'Operations Analyst',
    company: 'Air Canada',
    city: 'Montreal',
    province: 'QC',
    workStyle: 'On-site',
    source: 'Indeed',
    skills: ['operations', 'excel', 'sql', 'analytics', 'process', 'forecasting', 'communication'],
    seniority: 'mid',
    salary: '$75k–$98k CAD',
    postedDaysAgo: 4,
    closesInDays: 15,
    applicants: 49,
    summary: 'Find the delays hiding in a national airline operation and fix the process, not the slide.',
  },
  {
    id: 'slack-solutions',
    title: 'Solutions Engineer',
    company: 'Salesforce',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['salesforce', 'solutions', 'demo', 'communication', 'saas', 'integrations', 'crm'],
    seniority: 'mid',
    salary: '$105k–$145k CAD',
    postedDaysAgo: 1,
    closesInDays: 9,
    applicants: 37,
    summary: 'Turn messy customer problems into a working demo before the next call.',
  },
  {
    id: 'wealthsimple-design',
    title: 'Product Designer',
    company: 'Wealthsimple',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Remote',
    source: 'Company site',
    skills: ['figma', 'product design', 'fintech', 'research', 'prototyping', 'ui', 'ux'],
    seniority: 'senior',
    salary: '$130k–$165k CAD',
    postedDaysAgo: 0,
    closesInDays: 4,
    applicants: 16,
    summary: 'Make investing feel obvious. Senior craft and strong product taste required.',
    deeper: true,
  },
  {
    id: 'td-pm',
    title: 'Digital Product Manager',
    company: 'TD',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Hybrid',
    source: 'LinkedIn',
    skills: ['product', 'fintech', 'roadmaps', 'analytics', 'stakeholder', 'agile', 'mobile'],
    seniority: 'senior',
    salary: '$125k–$160k CAD',
    postedDaysAgo: 3,
    closesInDays: 12,
    applicants: 47,
    summary: 'Ship digital banking features that have to work the first time, at bank scale.',
  },
  {
    id: 'shopify-support-lead',
    title: 'Engineering Manager',
    company: 'Shopify',
    city: 'Toronto',
    province: 'ON',
    workStyle: 'Remote',
    source: 'LinkedIn',
    skills: ['management', 'leadership', 'coaching', 'react', 'ruby', 'hiring', 'product'],
    seniority: 'lead',
    salary: '$170k–$210k CAD',
    postedDaysAgo: 6,
    closesInDays: 18,
    applicants: 34,
    summary: 'Lead a product engineering team. You will still read code and still talk to merchants.',
  },
]

export function jobLocation(job: Pick<Job, 'city' | 'workStyle'>) {
  return `${job.city} · ${job.workStyle}`
}

const COMPETITOR_HOSTS = [
  'linkedin.com',
  'indeed.com',
  'glassdoor.com',
  'monster.com',
  'ziprecruiter.com',
  'workopolis.com',
  'eluta.ca',
]

export const COMPANY_CAREERS: Record<string, string> = {
  Shopify: 'https://www.shopify.com/careers',
  Wealthsimple: 'https://www.wealthsimple.com/en-ca/careers',
  Ada: 'https://www.ada.cx/careers',
  SSENSE: 'https://www.ssense.com/en-ca/careers',
  Hootsuite: 'https://www.hootsuite.com/about/careers',
  RBC: 'https://jobs.rbc.com',
  Nubank: 'https://international.nubank.com/careers',
  OpenText: 'https://careers.opentext.com',
  Figma: 'https://www.figma.com/careers',
  lululemon: 'https://careers.lululemon.com',
  TD: 'https://jobs.td.com',
  'Telus Health': 'https://www.telus.com/en/careers',
  CIBC: 'https://www.cibc.com/en/about-cibc/careers.html',
  Google: 'https://www.google.com/about/careers',
  Amazon: 'https://www.amazon.jobs',
  Thinkific: 'https://www.thinkific.com/careers',
  Clio: 'https://www.clio.com/about/careers',
  D2L: 'https://www.d2l.com/careers',
  Benevity: 'https://benevity.com/careers',
  'ATB Financial': 'https://www.atb.com/company/careers',
  CGI: 'https://www.cgi.com/en/careers',
  Lightspeed: 'https://www.lightspeedhq.com/careers',
  Wave: 'https://www.waveapps.com/careers',
  KOHO: 'https://www.koho.ca/careers',
  'Loblaw Digital': 'https://www.loblaw.ca/en/careers',
  'Canada Life': 'https://www.canadalife.com/about-us/careers.html',
  Suncor: 'https://www.suncor.com/en-ca/careers',
  Notion: 'https://www.notion.com/careers',
  HubSpot: 'https://www.hubspot.com/careers',
  Coveo: 'https://www.coveo.com/en/company/careers',
  Fairfax: 'https://www.fairfax.ca',
  'Air Canada': 'https://careers.aircanada.com',
  Salesforce: 'https://careers.salesforce.com',
}

export function isEmployerUrl(url: string) {
  try {
    const host = new URL(url).hostname.replace(/^www\./, '').toLowerCase()
    return !COMPETITOR_HOSTS.some((board) => host === board || host.endsWith(`.${board}`))
  } catch {
    return false
  }
}

export function jobHref(job: Pick<Job, 'company' | 'applyUrl'>) {
  const direct = job.applyUrl && isEmployerUrl(job.applyUrl) ? job.applyUrl : undefined
  const careers = COMPANY_CAREERS[job.company]
  return direct ?? careers ?? null
}
